# Server
server.port=8080
server.servlet.context-path=/IpsDashBoard
spring.web.resources.static-locations=classpath:/webapp/

# Oracle (keep for prod but fix connectivity first)
spring.datasource.url=jdbc:oracle:thin:@//hzzpoda-scan.nwc75.hubs:1521/svcdbbb
spring.datasource.username=ro_user
spring.datasource.password=SaViT@42KuM@R
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

# Logging
logging.level.root=INFO
logging.level.net.neology.ipsdashboard=DEBUG